// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ifmo/mpp/lab3/message.proto

public final class TMessagesProto {
  private TMessagesProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface TMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ifmo.mpp.lab3.TMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>uint32 type = 1;</code>
     * @return The type.
     */
    int getType();

    /**
     * <code>int64 size = 2;</code>
     * @return The size.
     */
    long getSize();

    /**
     * <code>repeated uint32 data = 3;</code>
     * @return A list containing the data.
     */
    java.util.List<Integer> getDataList();
    /**
     * <code>repeated uint32 data = 3;</code>
     * @return The count of data.
     */
    int getDataCount();
    /**
     * <code>repeated uint32 data = 3;</code>
     * @param index The index of the element to return.
     * @return The data at the given index.
     */
    int getData(int index);
  }
  /**
   * Protobuf type {@code ifmo.mpp.lab3.TMessage}
   */
  public  static final class TMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ifmo.mpp.lab3.TMessage)
      TMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use TMessage.newBuilder() to construct.
    private TMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TMessage() {
      data_ = emptyIntList();
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new TMessage();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private TMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              type_ = input.readUInt32();
              break;
            }
            case 16: {

              size_ = input.readInt64();
              break;
            }
            case 24: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                data_ = newIntList();
                mutable_bitField0_ |= 0x00000001;
              }
              data_.addInt(input.readUInt32());
              break;
            }
            case 26: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000001) != 0) && input.getBytesUntilLimit() > 0) {
                data_ = newIntList();
                mutable_bitField0_ |= 0x00000001;
              }
              while (input.getBytesUntilLimit() > 0) {
                data_.addInt(input.readUInt32());
              }
              input.popLimit(limit);
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          data_.makeImmutable(); // C
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ifmo.mpp.lab3.TMessagesProto.internal_static_ifmo_mpp_lab3_TMessage_descriptor;
    }

    @Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ifmo.mpp.lab3.TMessagesProto.internal_static_ifmo_mpp_lab3_TMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ifmo.mpp.lab3.TMessagesProto.TMessage.class, ifmo.mpp.lab3.TMessagesProto.TMessage.Builder.class);
    }

    public static final int TYPE_FIELD_NUMBER = 1;
    private int type_;
    /**
     * <code>uint32 type = 1;</code>
     * @return The type.
     */
    public int getType() {
      return type_;
    }

    public static final int SIZE_FIELD_NUMBER = 2;
    private long size_;
    /**
     * <code>int64 size = 2;</code>
     * @return The size.
     */
    public long getSize() {
      return size_;
    }

    public static final int DATA_FIELD_NUMBER = 3;
    private com.google.protobuf.Internal.IntList data_;
    /**
     * <code>repeated uint32 data = 3;</code>
     * @return A list containing the data.
     */
    public java.util.List<Integer>
        getDataList() {
      return data_;
    }
    /**
     * <code>repeated uint32 data = 3;</code>
     * @return The count of data.
     */
    public int getDataCount() {
      return data_.size();
    }
    /**
     * <code>repeated uint32 data = 3;</code>
     * @param index The index of the element to return.
     * @return The data at the given index.
     */
    public int getData(int index) {
      return data_.getInt(index);
    }
    private int dataMemoizedSerializedSize = -1;

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (type_ != 0) {
        output.writeUInt32(1, type_);
      }
      if (size_ != 0L) {
        output.writeInt64(2, size_);
      }
      if (getDataList().size() > 0) {
        output.writeUInt32NoTag(26);
        output.writeUInt32NoTag(dataMemoizedSerializedSize);
      }
      for (int i = 0; i < data_.size(); i++) {
        output.writeUInt32NoTag(data_.getInt(i));
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (type_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, type_);
      }
      if (size_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, size_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < data_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeUInt32SizeNoTag(data_.getInt(i));
        }
        size += dataSize;
        if (!getDataList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        dataMemoizedSerializedSize = dataSize;
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ifmo.mpp.lab3.TMessagesProto.TMessage)) {
        return super.equals(obj);
      }
      ifmo.mpp.lab3.TMessagesProto.TMessage other = (ifmo.mpp.lab3.TMessagesProto.TMessage) obj;

      if (getType()
          != other.getType()) return false;
      if (getSize()
          != other.getSize()) return false;
      if (!getDataList()
          .equals(other.getDataList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getType();
      hash = (37 * hash) + SIZE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getSize());
      if (getDataCount() > 0) {
        hash = (37 * hash) + DATA_FIELD_NUMBER;
        hash = (53 * hash) + getDataList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ifmo.mpp.lab3.TMessagesProto.TMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ifmo.mpp.lab3.TMessagesProto.TMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ifmo.mpp.lab3.TMessagesProto.TMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ifmo.mpp.lab3.TMessagesProto.TMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ifmo.mpp.lab3.TMessagesProto.TMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ifmo.mpp.lab3.TMessagesProto.TMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ifmo.mpp.lab3.TMessagesProto.TMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ifmo.mpp.lab3.TMessagesProto.TMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ifmo.mpp.lab3.TMessagesProto.TMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ifmo.mpp.lab3.TMessagesProto.TMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ifmo.mpp.lab3.TMessagesProto.TMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ifmo.mpp.lab3.TMessagesProto.TMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ifmo.mpp.lab3.TMessagesProto.TMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ifmo.mpp.lab3.TMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ifmo.mpp.lab3.TMessage)
        ifmo.mpp.lab3.TMessagesProto.TMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ifmo.mpp.lab3.TMessagesProto.internal_static_ifmo_mpp_lab3_TMessage_descriptor;
      }

      @Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ifmo.mpp.lab3.TMessagesProto.internal_static_ifmo_mpp_lab3_TMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ifmo.mpp.lab3.TMessagesProto.TMessage.class, ifmo.mpp.lab3.TMessagesProto.TMessage.Builder.class);
      }

      // Construct using ifmo.mpp.lab3.TMessagesProto.TMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        type_ = 0;

        size_ = 0L;

        data_ = emptyIntList();
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ifmo.mpp.lab3.TMessagesProto.internal_static_ifmo_mpp_lab3_TMessage_descriptor;
      }

      @Override
      public ifmo.mpp.lab3.TMessagesProto.TMessage getDefaultInstanceForType() {
        return ifmo.mpp.lab3.TMessagesProto.TMessage.getDefaultInstance();
      }

      @Override
      public ifmo.mpp.lab3.TMessagesProto.TMessage build() {
        ifmo.mpp.lab3.TMessagesProto.TMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public ifmo.mpp.lab3.TMessagesProto.TMessage buildPartial() {
        ifmo.mpp.lab3.TMessagesProto.TMessage result = new ifmo.mpp.lab3.TMessagesProto.TMessage(this);
        int from_bitField0_ = bitField0_;
        result.type_ = type_;
        result.size_ = size_;
        if (((bitField0_ & 0x00000001) != 0)) {
          data_.makeImmutable();
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.data_ = data_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ifmo.mpp.lab3.TMessagesProto.TMessage) {
          return mergeFrom((ifmo.mpp.lab3.TMessagesProto.TMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ifmo.mpp.lab3.TMessagesProto.TMessage other) {
        if (other == ifmo.mpp.lab3.TMessagesProto.TMessage.getDefaultInstance()) return this;
        if (other.getType() != 0) {
          setType(other.getType());
        }
        if (other.getSize() != 0L) {
          setSize(other.getSize());
        }
        if (!other.data_.isEmpty()) {
          if (data_.isEmpty()) {
            data_ = other.data_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureDataIsMutable();
            data_.addAll(other.data_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ifmo.mpp.lab3.TMessagesProto.TMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ifmo.mpp.lab3.TMessagesProto.TMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int type_ ;
      /**
       * <code>uint32 type = 1;</code>
       * @return The type.
       */
      public int getType() {
        return type_;
      }
      /**
       * <code>uint32 type = 1;</code>
       * @param value The type to set.
       * @return This builder for chaining.
       */
      public Builder setType(int value) {

        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 type = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearType() {

        type_ = 0;
        onChanged();
        return this;
      }

      private long size_ ;
      /**
       * <code>int64 size = 2;</code>
       * @return The size.
       */
      public long getSize() {
        return size_;
      }
      /**
       * <code>int64 size = 2;</code>
       * @param value The size to set.
       * @return This builder for chaining.
       */
      public Builder setSize(long value) {

        size_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 size = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearSize() {

        size_ = 0L;
        onChanged();
        return this;
      }

      private com.google.protobuf.Internal.IntList data_ = emptyIntList();
      private void ensureDataIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          data_ = mutableCopy(data_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated uint32 data = 3;</code>
       * @return A list containing the data.
       */
      public java.util.List<Integer>
          getDataList() {
        return ((bitField0_ & 0x00000001) != 0) ?
                 java.util.Collections.unmodifiableList(data_) : data_;
      }
      /**
       * <code>repeated uint32 data = 3;</code>
       * @return The count of data.
       */
      public int getDataCount() {
        return data_.size();
      }
      /**
       * <code>repeated uint32 data = 3;</code>
       * @param index The index of the element to return.
       * @return The data at the given index.
       */
      public int getData(int index) {
        return data_.getInt(index);
      }
      /**
       * <code>repeated uint32 data = 3;</code>
       * @param index The index to set the value at.
       * @param value The data to set.
       * @return This builder for chaining.
       */
      public Builder setData(
          int index, int value) {
        ensureDataIsMutable();
        data_.setInt(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated uint32 data = 3;</code>
       * @param value The data to add.
       * @return This builder for chaining.
       */
      public Builder addData(int value) {
        ensureDataIsMutable();
        data_.addInt(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated uint32 data = 3;</code>
       * @param values The data to add.
       * @return This builder for chaining.
       */
      public Builder addAllData(
          Iterable<? extends Integer> values) {
        ensureDataIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, data_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated uint32 data = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearData() {
        data_ = emptyIntList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ifmo.mpp.lab3.TMessage)
    }

    // @@protoc_insertion_point(class_scope:ifmo.mpp.lab3.TMessage)
    private static final ifmo.mpp.lab3.TMessagesProto.TMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ifmo.mpp.lab3.TMessagesProto.TMessage();
    }

    public static ifmo.mpp.lab3.TMessagesProto.TMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TMessage>
        PARSER = new com.google.protobuf.AbstractParser<TMessage>() {
      @Override
      public TMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<TMessage> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<TMessage> getParserForType() {
      return PARSER;
    }

    @Override
    public ifmo.mpp.lab3.TMessagesProto.TMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface TMessagesOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ifmo.mpp.lab3.TMessages)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .ifmo.mpp.lab3.TMessage item = 1;</code>
     */
    java.util.List<ifmo.mpp.lab3.TMessagesProto.TMessage>
        getItemList();
    /**
     * <code>repeated .ifmo.mpp.lab3.TMessage item = 1;</code>
     */
    ifmo.mpp.lab3.TMessagesProto.TMessage getItem(int index);
    /**
     * <code>repeated .ifmo.mpp.lab3.TMessage item = 1;</code>
     */
    int getItemCount();
    /**
     * <code>repeated .ifmo.mpp.lab3.TMessage item = 1;</code>
     */
    java.util.List<? extends ifmo.mpp.lab3.TMessagesProto.TMessageOrBuilder>
        getItemOrBuilderList();
    /**
     * <code>repeated .ifmo.mpp.lab3.TMessage item = 1;</code>
     */
    ifmo.mpp.lab3.TMessagesProto.TMessageOrBuilder getItemOrBuilder(
            int index);
  }
  /**
   * Protobuf type {@code ifmo.mpp.lab3.TMessages}
   */
  public  static final class TMessages extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ifmo.mpp.lab3.TMessages)
      TMessagesOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use TMessages.newBuilder() to construct.
    private TMessages(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TMessages() {
      item_ = java.util.Collections.emptyList();
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new TMessages();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private TMessages(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                item_ = new java.util.ArrayList<ifmo.mpp.lab3.TMessagesProto.TMessage>();
                mutable_bitField0_ |= 0x00000001;
              }
              item_.add(
                  input.readMessage(ifmo.mpp.lab3.TMessagesProto.TMessage.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          item_ = java.util.Collections.unmodifiableList(item_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ifmo.mpp.lab3.TMessagesProto.internal_static_ifmo_mpp_lab3_TMessages_descriptor;
    }

    @Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ifmo.mpp.lab3.TMessagesProto.internal_static_ifmo_mpp_lab3_TMessages_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ifmo.mpp.lab3.TMessagesProto.TMessages.class, ifmo.mpp.lab3.TMessagesProto.TMessages.Builder.class);
    }

    public static final int ITEM_FIELD_NUMBER = 1;
    private java.util.List<ifmo.mpp.lab3.TMessagesProto.TMessage> item_;
    /**
     * <code>repeated .ifmo.mpp.lab3.TMessage item = 1;</code>
     */
    public java.util.List<ifmo.mpp.lab3.TMessagesProto.TMessage> getItemList() {
      return item_;
    }
    /**
     * <code>repeated .ifmo.mpp.lab3.TMessage item = 1;</code>
     */
    public java.util.List<? extends ifmo.mpp.lab3.TMessagesProto.TMessageOrBuilder>
        getItemOrBuilderList() {
      return item_;
    }
    /**
     * <code>repeated .ifmo.mpp.lab3.TMessage item = 1;</code>
     */
    public int getItemCount() {
      return item_.size();
    }
    /**
     * <code>repeated .ifmo.mpp.lab3.TMessage item = 1;</code>
     */
    public ifmo.mpp.lab3.TMessagesProto.TMessage getItem(int index) {
      return item_.get(index);
    }
    /**
     * <code>repeated .ifmo.mpp.lab3.TMessage item = 1;</code>
     */
    public ifmo.mpp.lab3.TMessagesProto.TMessageOrBuilder getItemOrBuilder(
        int index) {
      return item_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < item_.size(); i++) {
        output.writeMessage(1, item_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < item_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, item_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ifmo.mpp.lab3.TMessagesProto.TMessages)) {
        return super.equals(obj);
      }
      ifmo.mpp.lab3.TMessagesProto.TMessages other = (ifmo.mpp.lab3.TMessagesProto.TMessages) obj;

      if (!getItemList()
          .equals(other.getItemList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getItemCount() > 0) {
        hash = (37 * hash) + ITEM_FIELD_NUMBER;
        hash = (53 * hash) + getItemList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ifmo.mpp.lab3.TMessagesProto.TMessages parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ifmo.mpp.lab3.TMessagesProto.TMessages parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ifmo.mpp.lab3.TMessagesProto.TMessages parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ifmo.mpp.lab3.TMessagesProto.TMessages parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ifmo.mpp.lab3.TMessagesProto.TMessages parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ifmo.mpp.lab3.TMessagesProto.TMessages parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ifmo.mpp.lab3.TMessagesProto.TMessages parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ifmo.mpp.lab3.TMessagesProto.TMessages parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ifmo.mpp.lab3.TMessagesProto.TMessages parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ifmo.mpp.lab3.TMessagesProto.TMessages parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ifmo.mpp.lab3.TMessagesProto.TMessages parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ifmo.mpp.lab3.TMessagesProto.TMessages parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ifmo.mpp.lab3.TMessagesProto.TMessages prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ifmo.mpp.lab3.TMessages}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ifmo.mpp.lab3.TMessages)
        ifmo.mpp.lab3.TMessagesProto.TMessagesOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ifmo.mpp.lab3.TMessagesProto.internal_static_ifmo_mpp_lab3_TMessages_descriptor;
      }

      @Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ifmo.mpp.lab3.TMessagesProto.internal_static_ifmo_mpp_lab3_TMessages_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ifmo.mpp.lab3.TMessagesProto.TMessages.class, ifmo.mpp.lab3.TMessagesProto.TMessages.Builder.class);
      }

      // Construct using ifmo.mpp.lab3.TMessagesProto.TMessages.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getItemFieldBuilder();
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        if (itemBuilder_ == null) {
          item_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          itemBuilder_.clear();
        }
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ifmo.mpp.lab3.TMessagesProto.internal_static_ifmo_mpp_lab3_TMessages_descriptor;
      }

      @Override
      public ifmo.mpp.lab3.TMessagesProto.TMessages getDefaultInstanceForType() {
        return ifmo.mpp.lab3.TMessagesProto.TMessages.getDefaultInstance();
      }

      @Override
      public ifmo.mpp.lab3.TMessagesProto.TMessages build() {
        ifmo.mpp.lab3.TMessagesProto.TMessages result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public ifmo.mpp.lab3.TMessagesProto.TMessages buildPartial() {
        ifmo.mpp.lab3.TMessagesProto.TMessages result = new ifmo.mpp.lab3.TMessagesProto.TMessages(this);
        int from_bitField0_ = bitField0_;
        if (itemBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            item_ = java.util.Collections.unmodifiableList(item_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.item_ = item_;
        } else {
          result.item_ = itemBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ifmo.mpp.lab3.TMessagesProto.TMessages) {
          return mergeFrom((ifmo.mpp.lab3.TMessagesProto.TMessages)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ifmo.mpp.lab3.TMessagesProto.TMessages other) {
        if (other == ifmo.mpp.lab3.TMessagesProto.TMessages.getDefaultInstance()) return this;
        if (itemBuilder_ == null) {
          if (!other.item_.isEmpty()) {
            if (item_.isEmpty()) {
              item_ = other.item_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureItemIsMutable();
              item_.addAll(other.item_);
            }
            onChanged();
          }
        } else {
          if (!other.item_.isEmpty()) {
            if (itemBuilder_.isEmpty()) {
              itemBuilder_.dispose();
              itemBuilder_ = null;
              item_ = other.item_;
              bitField0_ = (bitField0_ & ~0x00000001);
              itemBuilder_ =
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getItemFieldBuilder() : null;
            } else {
              itemBuilder_.addAllMessages(other.item_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ifmo.mpp.lab3.TMessagesProto.TMessages parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ifmo.mpp.lab3.TMessagesProto.TMessages) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<ifmo.mpp.lab3.TMessagesProto.TMessage> item_ =
        java.util.Collections.emptyList();
      private void ensureItemIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          item_ = new java.util.ArrayList<ifmo.mpp.lab3.TMessagesProto.TMessage>(item_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          ifmo.mpp.lab3.TMessagesProto.TMessage, ifmo.mpp.lab3.TMessagesProto.TMessage.Builder, ifmo.mpp.lab3.TMessagesProto.TMessageOrBuilder> itemBuilder_;

      /**
       * <code>repeated .ifmo.mpp.lab3.TMessage item = 1;</code>
       */
      public java.util.List<ifmo.mpp.lab3.TMessagesProto.TMessage> getItemList() {
        if (itemBuilder_ == null) {
          return java.util.Collections.unmodifiableList(item_);
        } else {
          return itemBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .ifmo.mpp.lab3.TMessage item = 1;</code>
       */
      public int getItemCount() {
        if (itemBuilder_ == null) {
          return item_.size();
        } else {
          return itemBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .ifmo.mpp.lab3.TMessage item = 1;</code>
       */
      public ifmo.mpp.lab3.TMessagesProto.TMessage getItem(int index) {
        if (itemBuilder_ == null) {
          return item_.get(index);
        } else {
          return itemBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .ifmo.mpp.lab3.TMessage item = 1;</code>
       */
      public Builder setItem(
          int index, ifmo.mpp.lab3.TMessagesProto.TMessage value) {
        if (itemBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureItemIsMutable();
          item_.set(index, value);
          onChanged();
        } else {
          itemBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .ifmo.mpp.lab3.TMessage item = 1;</code>
       */
      public Builder setItem(
          int index, ifmo.mpp.lab3.TMessagesProto.TMessage.Builder builderForValue) {
        if (itemBuilder_ == null) {
          ensureItemIsMutable();
          item_.set(index, builderForValue.build());
          onChanged();
        } else {
          itemBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ifmo.mpp.lab3.TMessage item = 1;</code>
       */
      public Builder addItem(ifmo.mpp.lab3.TMessagesProto.TMessage value) {
        if (itemBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureItemIsMutable();
          item_.add(value);
          onChanged();
        } else {
          itemBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .ifmo.mpp.lab3.TMessage item = 1;</code>
       */
      public Builder addItem(
          int index, ifmo.mpp.lab3.TMessagesProto.TMessage value) {
        if (itemBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureItemIsMutable();
          item_.add(index, value);
          onChanged();
        } else {
          itemBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .ifmo.mpp.lab3.TMessage item = 1;</code>
       */
      public Builder addItem(
          ifmo.mpp.lab3.TMessagesProto.TMessage.Builder builderForValue) {
        if (itemBuilder_ == null) {
          ensureItemIsMutable();
          item_.add(builderForValue.build());
          onChanged();
        } else {
          itemBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ifmo.mpp.lab3.TMessage item = 1;</code>
       */
      public Builder addItem(
          int index, ifmo.mpp.lab3.TMessagesProto.TMessage.Builder builderForValue) {
        if (itemBuilder_ == null) {
          ensureItemIsMutable();
          item_.add(index, builderForValue.build());
          onChanged();
        } else {
          itemBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ifmo.mpp.lab3.TMessage item = 1;</code>
       */
      public Builder addAllItem(
          Iterable<? extends ifmo.mpp.lab3.TMessagesProto.TMessage> values) {
        if (itemBuilder_ == null) {
          ensureItemIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, item_);
          onChanged();
        } else {
          itemBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .ifmo.mpp.lab3.TMessage item = 1;</code>
       */
      public Builder clearItem() {
        if (itemBuilder_ == null) {
          item_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          itemBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .ifmo.mpp.lab3.TMessage item = 1;</code>
       */
      public Builder removeItem(int index) {
        if (itemBuilder_ == null) {
          ensureItemIsMutable();
          item_.remove(index);
          onChanged();
        } else {
          itemBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .ifmo.mpp.lab3.TMessage item = 1;</code>
       */
      public ifmo.mpp.lab3.TMessagesProto.TMessage.Builder getItemBuilder(
          int index) {
        return getItemFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .ifmo.mpp.lab3.TMessage item = 1;</code>
       */
      public ifmo.mpp.lab3.TMessagesProto.TMessageOrBuilder getItemOrBuilder(
          int index) {
        if (itemBuilder_ == null) {
          return item_.get(index);  } else {
          return itemBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .ifmo.mpp.lab3.TMessage item = 1;</code>
       */
      public java.util.List<? extends ifmo.mpp.lab3.TMessagesProto.TMessageOrBuilder>
           getItemOrBuilderList() {
        if (itemBuilder_ != null) {
          return itemBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(item_);
        }
      }
      /**
       * <code>repeated .ifmo.mpp.lab3.TMessage item = 1;</code>
       */
      public ifmo.mpp.lab3.TMessagesProto.TMessage.Builder addItemBuilder() {
        return getItemFieldBuilder().addBuilder(
            ifmo.mpp.lab3.TMessagesProto.TMessage.getDefaultInstance());
      }
      /**
       * <code>repeated .ifmo.mpp.lab3.TMessage item = 1;</code>
       */
      public ifmo.mpp.lab3.TMessagesProto.TMessage.Builder addItemBuilder(
          int index) {
        return getItemFieldBuilder().addBuilder(
            index, ifmo.mpp.lab3.TMessagesProto.TMessage.getDefaultInstance());
      }
      /**
       * <code>repeated .ifmo.mpp.lab3.TMessage item = 1;</code>
       */
      public java.util.List<ifmo.mpp.lab3.TMessagesProto.TMessage.Builder>
           getItemBuilderList() {
        return getItemFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          ifmo.mpp.lab3.TMessagesProto.TMessage, ifmo.mpp.lab3.TMessagesProto.TMessage.Builder, ifmo.mpp.lab3.TMessagesProto.TMessageOrBuilder>
          getItemFieldBuilder() {
        if (itemBuilder_ == null) {
          itemBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              ifmo.mpp.lab3.TMessagesProto.TMessage, ifmo.mpp.lab3.TMessagesProto.TMessage.Builder, ifmo.mpp.lab3.TMessagesProto.TMessageOrBuilder>(
                  item_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          item_ = null;
        }
        return itemBuilder_;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ifmo.mpp.lab3.TMessages)
    }

    // @@protoc_insertion_point(class_scope:ifmo.mpp.lab3.TMessages)
    private static final ifmo.mpp.lab3.TMessagesProto.TMessages DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ifmo.mpp.lab3.TMessagesProto.TMessages();
    }

    public static ifmo.mpp.lab3.TMessagesProto.TMessages getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TMessages>
        PARSER = new com.google.protobuf.AbstractParser<TMessages>() {
      @Override
      public TMessages parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TMessages(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<TMessages> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<TMessages> getParserForType() {
      return PARSER;
    }

    @Override
    public ifmo.mpp.lab3.TMessagesProto.TMessages getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ifmo_mpp_lab3_TMessage_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ifmo_mpp_lab3_TMessage_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ifmo_mpp_lab3_TMessages_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ifmo_mpp_lab3_TMessages_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\033ifmo/mpp/lab3/message.proto\022\rifmo.mpp." +
      "lab3\"4\n\010TMessage\022\014\n\004type\030\001 \001(\r\022\014\n\004size\030\002" +
      " \001(\003\022\014\n\004data\030\003 \003(\r\"2\n\tTMessages\022%\n\004item\030" +
      "\001 \003(\0132\027.ifmo.mpp.lab3.TMessageB\020B\016TMessa" +
      "gesProtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_ifmo_mpp_lab3_TMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ifmo_mpp_lab3_TMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ifmo_mpp_lab3_TMessage_descriptor,
        new String[] { "Type", "Size", "Data", });
    internal_static_ifmo_mpp_lab3_TMessages_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ifmo_mpp_lab3_TMessages_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ifmo_mpp_lab3_TMessages_descriptor,
        new String[] { "Item", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
